services:
  - type: web
    name: marketplace-php
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./php/Dockerfile
    dockerContext: ./php
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: MarketplaceMZ
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: CHANGE_ME_GENERATE_WITH_php_artisan_key_generate
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://whatsapp-marketplace-mz.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: CHANGE_ME_DATABASE_URL_FROM_SUPABASE
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: PYTHON_URL
        value: https://marketplace-python.onrender.com
      - key: WAHA_URL
        value: https://marketplace-waha-1.onrender.com
      - key: WAHA_API_KEY
        value: marketplace_secret_key_2026
      - key: WEBHOOK_SECRET
        value: marketplace_secret_key_2026
      - key: ADMIN_API_KEY
        value: 0871@py
      - key: SUPER_ADMIN_EMAIL
        value: admin@marketplace.co.mz

  - type: web
    name: marketplace-python
    env: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./python/Dockerfile
    dockerContext: ./python
    healthCheckPath: /health
    envVars:
      - key: LARAVEL_URL
        value: https://whatsapp-marketplace-mz.onrender.com
      - key: PHP_API_URL
        value: https://whatsapp-marketplace-mz.onrender.com/api/mensagem
      - key: APP_URL
        value: https://whatsapp-marketplace-mz.onrender.com
      - key: WAHA_URL
        value: https://marketplace-waha-1.onrender.com
      - key: WAHA_API_KEY
        value: marketplace_secret_key_2026
      - key: ADMIN_API_KEY
        value: 0871@py
      - key: WAHA_SESSION
        value: default
      - key: TENANT_ID_DEFAULT
        value: "1"
      - key: PORT
        value: "5000"
      - key: DEBUG
        value: "false"

  - type: web
    name: marketplace-waha-1
    env: docker
    region: frankfurt
    plan: free
    image:
      url: devlikeapro/waha:latest
    disk:
      name: waha-data-1
      mountPath: /app/.media
      sizeGB: 1
    healthCheckPath: /health
    envVars:
      - key: WAHA_CORE_LOG_LEVEL
        value: info
      - key: WAHA_LISTENING_HOST
        value: "0.0.0.0"
      - key: WAHA_ENGINE
        value: WEBJS
      - key: WAHA_PORT
        value: "3000"
      - key: WAHA_SECRET
        value: marketplace_secret_key_2026
      - key: WAHA_STORE_MECHANISM
        value: file
      - key: WAHA_PERSISTENT_DATA
        value: "true"
